version: "3.7"

services:
  mysql:
    image: mysql:latest
    platform: linux/x86_64
    container_name: mysql_pokemon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pokemon"
      MYSQL_DATABASE: "pokemon"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
